apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubevirt/kubevirt/releases/download/v1.4.0/kubevirt-cr.yaml
patches:
  - target:
      kind: KubeVirt
      name: kubevirt
    patch: |-
      - op: replace
        path: /spec/configuration/developerConfiguration/useEmulation
        value: false
      - op: add
        path: /spec/configuration/developerConfiguration/featureGates
        value:
          - "Macvtap"
          - "GPU"
          - "HostDevices"
          - "VSOCK"
      - op: add
        path: /spec/configuration/permittedHostDevices
        value:
          pciHostDevices:
          - pciVendorSelector: "1002:0300"
            resourceName: "amd.com/gpu"
      - op: add
        path: /spec/configuration/network
        value:
          defaultNetworkInterface: masquerade
