apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt-images
  namespace: flux-system
spec:
  dependsOn:
    - name: cdi-instance
  interval: 2h
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Applying the YAML file directly by using the path to the apps folder and selecting just that file
  # or better, just pointing to the file if we move it to a folder.
  # I'll create a folder for it to keep it clean.
  path: ./apps/kubevirt-images
