apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zfs-provisioner
  namespace: flux-system
spec:
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/zfs-provisioner
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-discovery
  namespace: flux-system
spec:
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/node-feature-discovery
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: multus-cni
  namespace: flux-system
spec:
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/multus-cni
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt-instance-types
  namespace: flux-system
spec:
  interval: 2h
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/kubevirt-instance-types
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: template-crd
  namespace: flux-system
spec:
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/template-crd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt-templates
  namespace: flux-system
spec:
  dependsOn:
    - name: template-crd
  interval: 2h
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/kubevirt-templates
  targetNamespace: kubevirt
