apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # 1. Sync Logic (Folder pointers)
  - sync-manifests.yaml

  # 2. Infrastructure Configs (Local YAMLs)
  - metallb-config.yaml
  - zfs-storage-class.yaml

  # 3. Workloads & Dashboards
  - example-app.yaml
  - kubevirt-manager.yaml
  - headlamp.yaml
  - headlamp-auth.yaml
