apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - example-app.yaml
  - kubevirt-operator.yaml
  - kubevirt-cr.yaml
  - node-feature-discovery.yaml
  - kubevirt-manager.yaml
  - cdi-operator.yaml
  - cdi-cr.yaml
  - kubevirt-instance-types.yaml
  - zfs-provisioner.yaml
  - zfs-storage-class.yaml
  - multus-cni.yaml
  - network-configs.yaml
