apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - example-app.yaml
  - kubevirt-operator.yaml
  - kubevirt-cr.yaml
  - kubevirt-manager.yaml
  - cdi-operator.yaml
  - infra-syncs.yaml
  - zfs-storage-class.yaml
  - storage-sync.yaml
  - network-sync.yaml
  - custom-types-sync.yaml
  - images-sync.yaml
  - headlamp.yaml
  - headlamp-auth.yaml
