apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: multus-cni
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Applying the YAML file directly
  path: ./apps/network-configs
