apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zfs-provisioner
  namespace: flux-system
spec:
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/zfs-provisioner
