apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-localpv
allowVolumeExpansion: true
parameters:
  poolname: "rpool"
  thinprovision: "yes"
  recordsize: "128k"
  compression: "on"
provisioner: zfs.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
